In [5]:
import numpy as np 
numbers= np.array([2,3,4,5,7,11])
type(numbers)
print(numbers)

for row in numbers:
    for column in row:
        print(column, end="")
    print()
    

[ 2  3  4  5  7 11]


TypeError: 'numpy.int64' object is not iterable

In [20]:
import numpy as np
integers=np.array([2,4,5,6,7])
for i in integers.flat:
    print(i,end="")
    
print(np.zeros(5,int))
# print(np.oves((2,4),int))
np.full((3,5),13)

24567[0 0 0 0 0]


array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

In [40]:
import numpy as np

print(np.full((3,5),13))
print(np.arange(1,21).reshape(4,5))
print(np.arange(5))
print(np.arange(5,10))
print(np.arange(10,1,-2))
print(np.arange(1,100001).reshape(100,1000))
np.linspace(0.0,1.0,5)

[[13 13 13 13 13]
 [13 13 13 13 13]
 [13 13 13 13 13]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[0 1 2 3 4]
[5 6 7 8 9]
[10  8  6  4  2]
[[     1      2      3 ...    998    999   1000]
 [  1001   1002   1003 ...   1998   1999   2000]
 [  2001   2002   2003 ...   2998   2999   3000]
 ...
 [ 97001  97002  97003 ...  97998  97999  98000]
 [ 98001  98002  98003 ...  98998  98999  99000]
 [ 99001  99002  99003 ...  99998  99999 100000]]


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [46]:
import numpy as np
num=np.array([2,4,5,6,7])
print(num*2)
print(num**3)
print(num)
print(num>=4)
print(num==4)


[ 4  8 10 12 14]
[  8  64 125 216 343]
[2 4 5 6 7]
[False  True  True  True  True]
[False  True False False False]


In [54]:
import numpy as np
grades=np.array([[87,90,86],[100,87,90],[100,50,67]])
print(grades.sum())
print(grades.min())
print(grades.max())
print(grades.mean())
print(grades.std())
print(grades.var())

757
50
100
84.11111111111111
15.095580254163023
227.87654320987656


In [67]:
import numpy as np
num=np.array([1,4,7,9,97,81])
print(np.sqrt(num))
num2=np.arange(1,7)*10
print(num2)
num3=np.add(num,num2)#num &num2 must be equal length
print(num3)
print(np.multiply(num2,5))


[1.         2.         2.64575131 3.         9.8488578  9.        ]
[10 20 30 40 50 60]
[ 11  24  37  49 147 141]
[ 50 100 150 200 250 300]


In [79]:
import numpy as np
grade=np.array([[87,90,86],[100,87,90],[100,50,67]])
print(grade)
print(grade[0,1])
print()
print(grade[0:2])
print()
print(grade[:,0])
print()
print(grade[:,1:3])
print()
print(grade[:,[0,2]])

[[ 87  90  86]
 [100  87  90]
 [100  50  67]]
90

[[ 87  90  86]
 [100  87  90]]

[ 87 100 100]

[[90 86]
 [87 90]
 [50 67]]

[[ 87  86]
 [100  90]
 [100  67]]


In [85]:
import numpy as np
num=np.array([1,4,7,9,97,81])
num2=num.view()
print(num2)
print(id(num))
print(id(num2))
print()
num2=num[0:3]
print(num)
print(num2)

[ 1  4  7  9 97 81]
140015742965584
140015742965488

[ 1  4  7  9 97 81]
[1 4 7]


In [95]:
import numpy as np
grade=np.array([[87,90,86],[100,87,90],[100,50,67]])
print(grade)
print(grade.reshape(9,1)) #total length (like shallow copy)
print(grade)


[[ 87  90  86]
 [100  87  90]
 [100  50  67]]
[[ 87]
 [ 90]
 [ 86]
 [100]
 [ 87]
 [ 90]
 [100]
 [ 50]
 [ 67]]
[[ 87  90  86]
 [100  87  90]
 [100  50  67]]


In [ ]:
import pandas as pd
grade=[[87,90,86],[100,87,90],[100,50,67],'spsahd',"sg twegwreg"]
g=pd.DataFrame(grade)
pd.DataFrame()